### ISSUE TITLE
assignment to undeclared variable i

### ISSUE THREAD

**Issue by Antricks** [SpyrexDE/Bay.js#1]
There are multiple instances of for loops with undeclared variables like here
https://github.com/SpyrexDE/Bay.js/blob/4169e99e087586ba1ee83acf6e42c8936b765209/src/Bay.js#L97
or here:
https://github.com/SpyrexDE/Bay.js/blob/4169e99e087586ba1ee83acf6e42c8936b765209/src/Bay.js#L109

I would suggest using forEach loops or for elem of list loops. At least in Firefox this throws an error.

**Comment by SpyrexDE** [comment]
Ah okay, I only tested on chrome yet. Will fix that soon
